baseURL = "https://blog.aydrafting.com/"
uglyURLs = false
title = "Blog"
theme = "PaperMod"
languageCode = "en-us"
description = "Civil Engineering and Automation insights from AYDrafting's founder"
copyright = "© 2025 AYDrafting. All rights reserved."
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# Enable RSS and Search
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
mainSections = ["posts"]
ShowCodeCopyButtons = true

# Enhanced SEO and metadata
env = "production"
defaultTheme = "auto"
ShowRssButtonInSectionTermList = true
ShowToc = true
# images = ["LogoAYD.png"]  # Removed to prevent logo from showing in social previews
keywords = ["civil engineering", "automation", "BIM", "Revit", "Civil 3D", "infrastructure design"]
enableRobotsTXT = true
canonifyURLs = true
relativeURLs = false
enableEmoji = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Blog"
    contentDir = "content/en"

  [languages.ru]
    languageName = "Русский"
    weight = 2
    title = "Блог"
    contentDir = "content/ru"

    [languages.ru.params]
      # Optional localized params; fallback to defaults where not specified
      ShowReadingTime = true
      ShowPostNavLinks = true
      ShowBreadCrumbs = true
      mainSections = ["posts"]
      ShowCodeCopyButtons = true
      defaultTheme = "auto"
      ShowRssButtonInSectionTermList = true
      ShowToc = true

      [languages.ru.params.editPost]
      URL = "mailto: aydimir@aydrafting.com"
      Text = "Предложить исправления"
      appendFilePath = false

      [languages.ru.params.homeInfoParams]
      Title = "Добро пожаловать в блог Айдимира."
      Content = '''

Инженер и основатель [AYDrafting](https://www.aydrafting.com).

Увлекаюсь автоматизацией Revit и AutoCAD Civil 3D.

Подписывайтесь, если хотите следить за новостями или поговорить со мной:
'''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "monokai"      # or "dracula", "monokai", "github"
    codeFences = true
    guessSyntax = true
    lineNos = true
    noHl = false

[markup.goldmark.parser.attribute]
block = true

# OpenGraph and Twitter Card metadata
[params.editPost]
URL = "mailto: aydimir@aydrafting.com"
Text = "Suggest Changes"
appendFilePath = false

# Schema.org metadata
[params.schema]
type = "Person"
name = "Aydimir Aydimirov"
description = "Civil Engineer and Automation Specialist"
sameAs = [
    "https://www.linkedin.com/in/aydimir/",
    "https://www.youtube.com/@aydrafting"
]

[params.homeInfoParams]
Title = "Welcome to Aydimir's Blog"
Content = '''

Engineer & Founder of [AYDrafting](https://www.aydrafting.com).

Revit & AutoCAD Civil 3D Automation Enthusiast.

Subscribe to my channels to follow the journey or to reach out:
'''

[[params.socialIcons]]
name = "github"
url = "https://www.github.com/aydimir95/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/aydimir/"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/@aydrafting"

[[params.socialIcons]]
name = "Twitter"
url = "https://www.twitter.com/aydrafting/"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/aydrafting/"

[[params.socialIcons]]
name = "rss"
url = "index.xml"
